import GSMToolsCore
import SwiftUI
import UniformTypeIdentifiers

struct ReportsView: View {
    @Environment(\.colorScheme) private var scheme
    @EnvironmentObject private var model: AppModel
    @State private var exportRequest: ReportExportRequest?

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 14) {
                HeaderView(
                    title: "Reports",
                    subtitle: "Exportable run summaries. Device-level review and ranking live in Devices.",
                    infoBullets: [
                        "Each report is generated from a completed analysis run.",
                        "Open Devices when you need to inspect transmitter-level evidence before exporting."
                    ],
                    infoLegendItems: [
                        InfoPopoverLegendItem(
                            title: "Critical flags",
                            detail: "Material transmitter or fleet issues generated by the run.",
                            systemImage: "exclamationmark",
                            color: .vermilion
                        ),
                        InfoPopoverLegendItem(
                            title: "Warnings",
                            detail: "Review-level drifts, weak signals, or non-critical telemetry concerns.",
                            systemImage: "exclamationmark.triangle.fill",
                            color: .ochre
                        ),
                        InfoPopoverLegendItem(
                            title: "Informational flags",
                            detail: "Context notes, usually missing baseline or unavailable comparison data.",
                            systemImage: "info",
                            color: .fallback
                        ),
                        InfoPopoverLegendItem(
                            title: "No generated flags",
                            detail: "The run did not produce report-level flags; review Devices for the full evidence.",
                            systemImage: "checkmark",
                            color: .green
                        )
                    ]
                )

                if model.reports.isEmpty {
                    ContentUnavailableView("No reports", systemImage: "doc.text", description: Text("Start a run to generate a diagnostic report."))
                        .frame(minHeight: 260)
                        .cttCard()
                } else {
                    LazyVStack(spacing: 12) {
                        ForEach(model.reports) { report in
                            ReportCard(report: report, run: run(for: report), exportRequest: $exportRequest)
                        }
                    }
                }
            }
            .padding(18)
        }
        .background(CTTColor.canvas(scheme))
        .fileExporter(
            isPresented: Binding(
                get: { exportRequest != nil },
                set: { if !$0 { exportRequest = nil } }
            ),
            document: exportRequest.map { ReportExportDocument(report: $0.report, format: $0.format) },
            contentType: exportRequest?.format.contentType ?? .plainText,
            defaultFilename: exportRequest?.defaultFilename ?? "report"
        ) { result in
            switch result {
            case let .success(url):
                if let exportRequest {
                    model.export(report: exportRequest.report, format: exportRequest.format, to: url)
                }
            case let .failure(error):
                model.presentError(error.localizedDescription)
            }
            exportRequest = nil
        }
    }

    private func run(for report: Report) -> AnalysisRun? {
        guard let runId = report.runId else { return nil }
        return model.runs.first { $0.id == runId }
    }
}

private struct ReportCard: View {
    @Environment(\.colorScheme) private var scheme
    @EnvironmentObject private var model: AppModel
    let report: Report
    let run: AnalysisRun?
    @Binding var exportRequest: ReportExportRequest?

    var body: some View {
        VStack(alignment: .leading, spacing: 13) {
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 5) {
                    Text(displayTitle)
                        .font(.system(size: 18, weight: .bold))
                        .foregroundStyle(CTTColor.ink(scheme))
                        .lineLimit(1)
                        .truncationMode(.middle)
                    Text(dataUsed)
                        .font(.system(size: 12, design: .monospaced))
                        .foregroundStyle(CTTColor.fg3(scheme))
                        .lineLimit(2)
                }

                Spacer()

                Text(verdictText)
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(.white)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(verdictColor)
                    .clipShape(RoundedRectangle(cornerRadius: 5))
                    .help("Report status is derived from generated run flags.")
            }

            Text(report.summary)
                .font(.system(size: 13))
                .foregroundStyle(CTTColor.fg2(scheme))

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 112), spacing: 8)], spacing: 8) {
                ReportMetric(value: "\(report.metrics.count)", label: "metrics")
                ReportMetric(value: "\(report.flags.filter { $0.severity == .critical }.count)", label: "critical")
                ReportMetric(value: "\(report.flags.filter { $0.severity == .warning }.count)", label: "warnings")
                ReportMetric(value: "\(run?.selectedIMEIs.count ?? 0)", label: "devices")
            }

            HStack(spacing: 8) {
                Button {
                    if let run {
                        model.openResults(for: run)
                    }
                } label: {
                    Label("Open Devices", systemImage: "waveform.path.ecg")
                }
                .disabled(run == nil)

                Menu {
                    ForEach(ReportExportFormat.allCases, id: \.self) { format in
                        Button(format.displayName) {
                            exportRequest = ReportExportRequest(report: report, format: format)
                        }
                    }
                } label: {
                    Label("Export", systemImage: "square.and.arrow.up")
                }
                .menuStyle(.button)

                Spacer()

                Text(Formatters.shortDateTime.string(from: report.generatedAt))
                    .font(.system(size: 12, design: .monospaced))
                    .foregroundStyle(CTTColor.fg3(scheme))
            }
            .controlSize(.small)
        }
        .padding(14)
        .background(CTTColor.paper(scheme))
        .clipShape(RoundedRectangle(cornerRadius: 9))
        .overlay {
            RoundedRectangle(cornerRadius: 9)
                .stroke(CTTColor.line2(scheme), lineWidth: 1)
        }
    }

    private var dataUsed: String {
        guard let run else {
            return "Data used: saved report · \(Formatters.shortDateTime.string(from: report.generatedAt))"
        }
        if let mode = run.analysisMode, mode.usesPerDeviceDeploymentWindows {
            return "\(mode.displayName) · per-device deployment windows · pull range \(Formatters.shortDateTime.string(from: run.startDate)) → \(Formatters.shortDateTime.string(from: run.endDate))"
        }
        return "\(run.analysisMode?.displayName ?? "selected period") · \(Formatters.shortDateTime.string(from: run.startDate)) → \(Formatters.shortDateTime.string(from: run.endDate))"
    }

    private var displayTitle: String {
        normalizedRunLabel(report.title)
    }

    private var verdictText: String {
        if report.flags.contains(where: { $0.severity == .critical }) { return "Critical flags" }
        if report.flags.contains(where: { $0.severity == .warning }) { return "Warnings" }
        if report.flags.contains(where: { $0.severity == .info }) { return "Informational flags only" }
        return "No generated flags"
    }

    private var verdictColor: Color {
        if report.flags.contains(where: { $0.severity == .critical }) { return CTTColor.vermilion(scheme) }
        if report.flags.contains(where: { $0.severity == .warning }) { return CTTColor.ochre(scheme) }
        return CTTColor.green(scheme)
    }
}

private extension AnalysisStudyMode {
    var usesPerDeviceDeploymentWindows: Bool {
        switch self {
        case .sinceDeviceDeployments, .compareDeviceDeploymentWindows:
            return true
        default:
            return false
        }
    }
}

private struct ReportMetric: View {
    @Environment(\.colorScheme) private var scheme
    let value: String
    let label: String

    var body: some View {
        VStack(alignment: .leading, spacing: 5) {
            Text(value)
                .font(.system(size: 20, weight: .bold, design: .monospaced))
                .foregroundStyle(CTTColor.ink(scheme))
            Text(label)
                .font(.system(size: 11))
                .foregroundStyle(CTTColor.fg3(scheme))
        }
        .padding(10)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(CTTColor.panel(scheme))
        .clipShape(RoundedRectangle(cornerRadius: 8))
    }
}

struct ReportExportRequest: Identifiable {
    var report: Report
    var format: ReportExportFormat

    var id: String { "\(report.id.uuidString)-\(format.rawValue)" }

    var defaultFilename: String {
        "\(normalizedRunLabel(report.title).replacingOccurrences(of: "/", with: "-")).\(format.fileExtension)"
    }
}

private func normalizedRunLabel(_ value: String) -> String {
    if value.hasPrefix("Pull ") {
        return "Analysis " + value.dropFirst("Pull ".count)
    }
    if value.hasPrefix("Investigation ") {
        return "Draft Analysis " + value.dropFirst("Investigation ".count)
    }
    return value
}

private struct ReportExportDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.plainText, .commaSeparatedText, .pdf] }

    var report: Report
    var format: ReportExportFormat

    init(report: Report, format: ReportExportFormat) {
        self.report = report
        self.format = format
    }

    init(configuration: ReadConfiguration) throws {
        self.report = Report(title: "Imported", summary: "", metrics: [], flags: [])
        self.format = .markdown
    }

    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        let exporter = ReportExporter()
        let data: Data
        switch format {
        case .markdown:
            data = exporter.markdownData(for: report)
        case .csv:
            data = exporter.csvData(for: report)
        case .pdf:
            data = exporter.pdfData(for: report)
        }
        return FileWrapper(regularFileWithContents: data)
    }
}

private extension ReportExportFormat {
    var contentType: UTType {
        switch self {
        case .markdown:
            return .plainText
        case .csv:
            return .commaSeparatedText
        case .pdf:
            return .pdf
        }
    }
}
